### ISSUE TITLE
Error occurred when executing FaceSwapGenerationInpaint:  VaeImageProcessor.preprocess() got an unexpected keyword argument 'crops_coords'

### ISSUE THREAD

**Issue by sanasigma** [nosiu/comfyui-instantId-faceswap#1]
![image](https://github.com/nosiu/comfyui-instantId-faceswap/assets/36327461/dfe47c34-5a25-4a4c-ba47-d882f842ce82)
used juggernaut xl checkpoint

**Comment by nosiu** [comment]
Hi @sanasigma you need to upgrade diffusers. It works with 0.25.0 version. `pip show diffusers` to view your current version
`pip install -U diffusers` to upgrade`

**Comment by wangzy85222** [comment]
> Hi @sanasigma you need to upgrade diffusers. It works with 0.25.0 version. `pip show diffusers` to view your current version `pip install -U diffusers` to upgrade`

diffuers==0.26.3 but still got the same problem help please @nosiu

**Comment by nosiu** [comment]
@wangzy85222 it works with the version of diffusers 0.26.3, just tested it.

**Comment by Skeletonpay** [comment]
same error on 0.26.3

**Comment by bigbrotherr** [comment]
I just updated diffusers to Version: 0.29.2, but I still get the same issue. Any fix?

**Comment by nosiu** [comment]
> I just updated diffusers to Version: 0.29.2, but I still get the same issue. Any fix?

This is connected ONLY to the wrong diffusers version. If you are getting this error it means your ComfyUI is using the wrong diffusers. The last tested and recommended version is 0.26.3 (or something like that, it's in the readme)

If you downgrade to 0.26.3 and still get this error it means you have more than one environment and you downgraded the wrong one.

**Comment by nosiu** [comment]
no longer relevant, since the version update
